# Generated by Django 4.1.7 on 2023-03-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='intro',
            field=models.CharField(max_length=350, verbose_name='Анонс'),
        ),
    ]
